services:
  wallos:
    image: bellamy/wallos@sha256:46f25daeebedbe00f409abdc82f07d1bde6818dc9fee8b360b0b09c453c4b999
    container_name: wallos
    restart: unless-stopped
    volumes:
      - ./db:/var/www/html/db
      - ./logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=America/Toronto
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallos.rule=Host(`wallos.thinkcenter.dev`)
      - traefik.http.routers.wallos.entrypoints=websecure
      - traefik.http.services.wallos.loadbalancer.server.port=80
networks:
  thinknetwork:
    external: true
