services:
  wallos:
    image: bellamy/wallos@sha256:9f1bbd7f24e2afdac64ff0985ef801d48f63086540a0844fc05727642bb5360a
    container_name: wallos
    restart: unless-stopped
    volumes:
      - ./db:/var/www/html/db
      - ./logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=America/Toronto
    networks:
      - thinknetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallos.rule=Host(`wallos.thinkcenter.dev`)
      - traefik.http.routers.wallos.entrypoints=websecure
      - traefik.http.services.wallos.loadbalancer.server.port=80
networks:
  thinknetwork:
    external: true
